# Builds wasm/scan.rs and writes extension/scanner-wasm.js (the module as base64),
# then rebuilds hexlock-extension.zip. Needs Rust with the wasm32-unknown-unknown target.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$rustc = Join-Path $env:USERPROFILE '.cargo\bin\rustc.exe'
$wasm = Join-Path $env:TEMP 'hexlock-scan.wasm'

& $rustc --target wasm32-unknown-unknown --crate-type cdylib -C opt-level=3 -C panic=abort -C strip=symbols `
    (Join-Path $PSScriptRoot 'scan.rs') -o $wasm
if ($LASTEXITCODE -ne 0) { throw 'rustc failed' }

$b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($wasm))
$js = "// Generated by wasm/build.ps1 from wasm/scan.rs. Do not edit.`nwindow.__hexlockWasm = `"$b64`";`n"
[IO.File]::WriteAllText((Join-Path $root 'extension\scanner-wasm.js'), $js)

Add-Type -AssemblyName System.IO.Compression, System.IO.Compression.FileSystem
$zipPath = Join-Path $root 'hexlock-extension.zip'
if (Test-Path $zipPath) { [IO.File]::Delete($zipPath) }
$zip = [IO.Compression.ZipFile]::Open($zipPath, 'Create')
Get-ChildItem (Join-Path $root 'extension') -File | ForEach-Object {
    [void][IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, "extension/$($_.Name)")
}
$zip.Dispose()
"Built scanner-wasm.js ($((Get-Item $wasm).Length) byte module) and hexlock-extension.zip"
